apiVersion: apps/v1
kind: Deployment
metadata:
  name: program1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: program1
  template:
    metadata:
      labels:
        app: program1
    spec:
      containers:
        - name: program1
          image: us-docker.pkg.dev/liquid-fort-453318-q8/csci-5409-k8/program1:latest
          volumeMounts:
            - name: standard-volume
              mountPath: /shail_pv_volume_k8
      volumes:
        - name: standard-volume
          persistentVolumeClaim:
            claimName: k8-pvc-standard-rwo
