apiVersion: apps/v1
kind: Deployment
metadata:
  name: program1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: program1
  template:
    metadata:
      labels:
        app: program1
    spec:
      containers:
        - name: program1
          image: us-docker.pkg.dev/liquid-fort-453318-q8/k8-assignment-registry/program1:latest
          volumeMounts:
            - name: storage-volume
              mountPath: /pv_dir
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: k8-pvc-standard
